## Receives player input and calls [method AbilityComponent.performAbility] to perform an [Ability].
## An [Ability] may be a special skill like "Heal", or a spell like "Fireball", or a trivial command like "Examine".
## Some abilities may require a target entity or object to be chosen, and may cost a [Stat] to be used.
## If the [AbilityComponent] requests a target, then a subclass of [AbilityTargetingComponentBase] is added to the Entity to prompt the player to choose a target.
## To display UI buttons for Abilities, use [AbilityButton] & [AbilityButtonsList].
## TIP: To execute Abilities via keyboard shortcuts or gamepad buttons, edit the Project Settings' Input Map,
## and add Godot input actions with names matching [member GlobalInput.Actions.abilityPrefix] + [member Ability.name] e.g. `ability_dash`.
## Requirements: [AbilityComponent]

class_name AbilityControlComponent
extends Component


#region Parameters
## A subclass of [AbilityTargetingComponentBase] to add to the parent [Entity] to present a UI to the player for choosing a target for [Ability]s which require a target, such as a "Fireball" spell or a "Talk" command.
@export_file("*AbilityTargeting*Component.tscn") var targetingComponentPath: String = "res://Components/Control/AbilityTargetingPositionComponent.tscn" # Exclude the abstract "Base" components.

@export var isEnabled: bool = true:
	set(newValue):
		if newValue != isEnabled:
			isEnabled = newValue
			self.set_process_input(isEnabled)
			self.set_process_unhandled_input(isEnabled)

#endregion


#region Signals
# In AbilityComponent
#endregion


#region Dependencies

@onready var abilityComponent: AbilityComponent = coComponents.AbilityComponent # TBD: Static or dynamic?

func getRequiredComponents() -> Array[Script]:
	return [AbilityComponent]

#endregion


#region Input & Execution

## Handles "synthetic" [InputEventAction] events generated by [AbilityButton] etc.
func _input(event: InputEvent) -> void:
	if not isEnabled or not event is InputEventAction: return

	# Just get an Ability's name, if any, and forward it to AbilityComponent.performAbility()

	var eventAction: InputEventAction = event as InputEventAction
	var eventName:   StringName = eventAction.action
	if debugMode: printDebug("_input() eventName: " + eventName)

	# Is it a "special" Ability?
	# NOTE: Compare in lowercase to reduce typos/mistakes/bugs
	if not eventName.to_lower().begins_with(GlobalInput.Actions.abilityPrefix.to_lower()): return

	var abilityName: StringName = eventName.trim_prefix(GlobalInput.Actions.abilityPrefix)
	if  abilityComponent:
		abilityComponent.performAbility(abilityName)
		self.get_viewport().set_input_as_handled()


## Handles keyboard shortcuts/controller buttons mapped to Abilities
func _unhandled_input(event: InputEvent) -> void:
	# TBD: Execute Ability shortcuts on press or on release?
	# TBD: According to Godot documentation: "For keyboard shortcuts, consider using _shortcut_input() instead, as it is called before this method. Finally, to handle keyboard events, consider using _unhandled_key_input() for performance reasons."

	if not isEnabled or not event.is_action_type() or not event.is_pressed() \
	or (event is InputEventKey and event.is_echo()): return # Prevent held keys from spamming abilities

	if abilityComponent:
		# See if a keyboard shortcut or gamepad button etc. matches any Ability, and execute it
		var ability: Ability = abilityComponent.findAbilityForInputEvent(event)
		if  ability:
			abilityComponent.performAbility(ability.name)
			self.get_viewport().set_input_as_handled()


#endregion


#region Target Selection

func _ready() -> void:
	Tools.connectSignal(abilityComponent.didRequestTarget, self.onAbilityComponent_didRequestTarget)


func onAbilityComponent_didRequestTarget(ability: Ability, source: Entity) -> void:
	if not isEnabled: return
	if debugMode: printDebug(str("onAbilityComponent_didRequestTarget() ", ability, ", source: ", source))
	if source == self.entity: createTargetingComponent(ability) # Create & add a component which prompt the player to choose a target.
	else: printDebug(str("Ability source: ", source, " is not the parent entity: ", entity))


func createTargetingComponent(abilityToPerform: Ability) -> AbilityTargetingComponentBase:
	var targetingComponent: AbilityTargetingComponentBase = SceneManager.instantiateSceneFromPath(targetingComponentPath)

	if not targetingComponent:
		printWarning(str("Cannot instantiate a subclass of AbilityTargetingComponentBase: ", targetingComponentPath))
		return null

	targetingComponent.ability = abilityToPerform
	entity.addComponent(targetingComponent)
	# GlobalUI.abilityDidRequestTarget.emit(abilityToPerform, entity) # This should be emitted by AbilityComponent next to its `didRequestTarget` as that's the first point where a target is requested.
	return targetingComponent

#endregion
