## A unified state of control input for other components to act upon. The source may be a meatspace player, an AI agent script or a "demo/attract mode" recording etc.
## A main advantage of having a shared input state versus checking [method Node._input] directly is that other components/scripts can modify the shared state. e.g. a [PlatformerPatrolComponent] "injecting" movement into a [PlatformerPhysicsComponent]
## TIP: Most components/scripts only need to connect to simplified signals such as [signal didUpdateMovementDirection] etc. instead of processing [InputEvent]s via [signal didProcessInput]
## NOTE: Does NOT check mouse motion input; only clicks.
## ATTENTION: If mouse click events are not reaching this component, check the [member Control.mouse_filter] property of any overlaying nodes such as UI,
## and set it to [constant Control.MOUSE_FILTER_PASS] or [constant Control.MOUSE_FILTER_IGNORE]
## NOTE: PERFORMANCE: To reduce overhead, small independent components may do their own input polling. Therefore, this [InputComponent] makes most sense when a chain of multiple components depend upon it, such as [TurningControlComponent] + [ThrustControlComponent]
## TIP: Other components/scripts should check the DERIVED properties like [member horizontalInput] instead of directly processing an [InputEvent] on their own.
## TIP: May be subclassed for AI-control or pre-recorded demos or "attract mode" etc.
## Requirements: AFTER (below in the Scene Tree) all components that depend on player/AI control, because input events propagate UPWARD from the BOTTOM of the Scene Tree nodes list.

class_name InputComponent
extends Component


#region Parameters

## Disables all input processing & updates.
## ALERT: Clears all flags and vectors when disabled, but does NOT poll any ongoing "held" input state when re-enabled.
@export var isEnabled: bool = true:
	set(newValue):
		if newValue != isEnabled:
			isEnabled = newValue
			self.setAllProcesses()
			if isEnabled: pass # TBD: Call resyncAllInputs() to automatically resume held inputs, or wait for a re-press?
			else: clearAllInputs()

## If `false` then system input events are not processed,
## but this component may still be manually modified and used by other components, such as AI agents or demo scripts.
## [method handleEvent] & [method processMonitoredInputActions] may be called manually at any time,
## e.g. to process synthetic [InputEvent]s generated by gameplay code.
## IMPORTANT: Turn this OFF for enemies & NPCs!
@export var isPlayerControlled: bool = true:
	set(newValue):
		if newValue != isPlayerControlled:
			isPlayerControlled = newValue
			self.setAllProcesses()

## Multiplies each of the [param movementDirection]'s axes, i.e. the primary movement control, including the Left Joystick & D-pad.
## TIP: Negative values invert player/AI control. e.g. (-1, 1) will flip the horizontal walking direction.
@export var movementDirectionScale:	Vector2 = Vector2.ONE

## Multiplies each of the [param aimDirection]'s axes, which is usually provided by the Right Joystick.
## TIP: Negative values invert the camera control, e.g. (1, -1) will flip the vertical camera axis.
@export var aimDirectionScale:		Vector2 = Vector2.ONE

@export_group("Joystick vs Mouse")

## If `true`, then any movement of any gamepad joystick sets [member shouldSuppressMouseMotion] if [member movementDirection] is not (0,0).
## This resolves conflicts between components such as [MouseTrackingComponent] vs. [PositionControlComponent],
## allowing the player to move with the Left Joystick (for example) by temporarily ignoring mouse motion.
## Clicking any mouse button reenables mouse-controlled movement/aiming.
@export var shouldJoystickMovementSuppressMouse: bool = false

## If `true`, then any movement of any gamepad joystick sets [member shouldSuppressMouseMotion] if [member aimDirection] is not (0,0).
## This resolves conflicts between components such as [MouseRotationComponent] vs. [TurningControlComponent],
## allowing the player to aim a gun or move a cursor with the Right Joystick (for example) by temporarily ignoring mouse motion.
## Clicking any mouse button reenables mouse-controlled movement/aiming.
@export var shouldJoystickAimingSuppressMouse:   bool = true


@export_group("Event Processing")

## If `true` (default) then only [method Node._unhandled_input] is processed to catch the input events that are NOT consumed by other components/scripts/nodes.
## If `false` then [method Node._input] is processed, to catch ALL events, even if they were already handled by other nodes.
@export var shouldProcessUnhandledInputOnly: bool = true:
	set(newValue):
		if newValue != shouldProcessUnhandledInputOnly:
			shouldProcessUnhandledInputOnly = newValue
			self.setAllProcesses()

## If `true` (default) then an [InputEvent] is ignored if [method InputEvent.is_echo],
## i.e. a repeated event "echo" generated while holding a button or key pressed down.
@export var shouldIgnoreEchoes: bool = true # TBD: Should this default to `true`?

## If `true`, then [InputEvent]s are prevented from bubbling up the Scene Tree if they include any of the input actions processed by this component, such as movement, jumping, shooting etc.
## May improve performance.
## WARNING: This will prevent any OTHER [InputComponent]s from receiving events! Use this when ONLY ONE character should be controlled.
@export var shouldSetEventsAsHandled: bool = false # DESIGN: Let's default to `false` because disabling event propagation should be an explicit decision: we may forget about it and wonder why other scripts aren't receiving input.

## The list of input actions to watch for and include in [member inputActionsPressed]
## Because dummy Godot doesn't let us directly get all the input actions from an [InputEvent],
## we have to manually check every possibility, so here we shorten that list of possible events.
@export var inputActionsToMonitor: PackedStringArray = [
	GlobalInput.Actions.jump,
	GlobalInput.Actions.fire,
	GlobalInput.Actions.interact,
	]

#endregion


#region State
# TBD: Better names? "Input" → "Vector"? "Direction" → "Axis"?
# TBD: @export_storage

## A list of all the input actions from [constant inputActionsToMonitor] that are currently pressed.
var inputActionsPressed: PackedStringArray

## The primary movement input from the combined horizontal + vertical axes. Includes the Left Joystick & the D-pad.
## NOTE: Diagonal movement is "normalized" as polled via [method Input.get_vector] e.g. up+right = (0.707, -0.707). For "raw" axes, use [member horizontalInput] and [member verticalInput]
## ALERT: This property is NOT modified on "echo" events (keys held down); ONLY on CHANGES!
## ALERT: Directly modifying this vector does NOT automatically update [member horizontalInput] or [member verticalInput]
## TIP: Call [method setMovementInputs] to properly update related state and apply normalization etc.
var movementDirection: Vector2:
	set(newValue):
		if newValue != movementDirection: # Ignore "echoes" (repeated events generated when the same input is pressed and held)
			var difference: Vector2 = newValue - movementDirection
			movementDirection = newValue
			if not difference.is_zero_approx(): didUpdateMovementDirection.emit(movementDirection, difference)

## The primary X axis. Includes the Left Joystick & the D-pad.
## NOTE:  During diagonal movement this axis is a "raw" value, polled via [method Input.get_axis] e.g. up+right = 1.0 instead of 0.707; for "normalized" diagonals, use [member movementDirection]
## ALERT: Directly modifying this value does NOT automatically update [member movementDirection]
var horizontalInput: float:
	set(newValue):
		if newValue != horizontalInput:
			horizontalInput = newValue
			if not is_zero_approx(horizontalInput):
				if signf(lastNonzeroHorizontalInput) != signf(horizontalInput): # NOTE: Emit signals ONLY IF the direction CHANGES, not when movement STOPS.
					if debugMode: printDebug(str("didChangeHorizontalDirection: ", lastNonzeroHorizontalInput, " → ", horizontalInput))
					didChangeHorizontalDirection.emit()
				lastNonzeroHorizontalInput = horizontalInput

var lastNonzeroHorizontalInput: float ## The last NON-ZERO [member horizontalInput] received. May be used to determine where a character should be facing etc.

## The primary Y axis. Includes the Left Joystick & the D-pad.
## NOTE:  During diagonal movement this axis is a "raw" value, polled via [method Input.get_axis] e.g. up+right = -1.0 instead of -0.707; for "normalized" diagonals, use [member movementDirection]
## ALERT: Directly modifying this value does NOT automatically update [member movementDirection]
var verticalInput: float:
	set(newValue):
		if newValue != verticalInput:
			verticalInput = newValue
			if not is_zero_approx(verticalInput):
				if signf(lastNonzeroVerticalInput) != signf(verticalInput):  # NOTE: Emit signals ONLY IF the direction CHANGES, not when movement STOPS.
					if debugMode: printDebug(str("didChangeVerticalDirection: ",   lastNonzeroVerticalInput, " → ", verticalInput))
					didChangeVerticalDirection.emit()
				lastNonzeroVerticalInput = verticalInput

var lastNonzeroVerticalInput: float ## The last NON-ZERO [member verticalInput] received. May be used to determine where a character should be facing etc.

var aimDirection:	Vector2:	## The Right Joystick. May be used as the "look" direction for moving the camera, or for aiming a weapon in dual-stick shoot-em-ups etc.
	set(newValue):
		if newValue != aimDirection:
			var difference: Vector2 = newValue - aimDirection
			aimDirection = newValue
			if not difference.is_zero_approx(): didUpdateAimDirection.emit(aimDirection, difference)
		
var turnInput:		float:	## The horizontal X axis for the Left Joystick (NOT D-pad). May be identical to [member horizontalInput]. TBD: Include D-Pad?
	set(newValue):
		if newValue != turnInput:
			var difference: float = newValue - turnInput
			turnInput = newValue
			if not is_zero_approx(difference): didUpdateTurnInput.emit(turnInput, difference)
			
var thrustInput:	float:	## The vertical Y axis for the Left Joystick (NOT D-pad) representing "forward" or "backward". May be the INVERSE of [member verticalInput] because Godot's Y axis is negative for UP, but for joystick input UP is POSITIVE. TBD: Include D-Pad?
	set(newValue):
		if newValue != thrustInput:
			var difference: float = newValue - thrustInput
			thrustInput = newValue
			if not is_zero_approx(difference): didUpdateThrustInput.emit(thrustInput, difference)

## The most recent [InputEvent] received by [method handleEvent]
## NOTE: Only input "action" events where [method InputEvent.is_action_type] are included.
## WARNING: When properties such as [member movementDirection] are manually modified,
## the [member lastInputEvent] may be a PREVIOUS older event; do NOT rely on this when handling signals such as [signal didUpdateMovementDirection] etc.
var lastInputEvent:	InputEvent

## If `true`, then the next [method _input] or [method _unhandled_input] is skipped ONCE, and then this flag is reset.
## May be used to temporarily suppress player control, e.g. to implement automatic/scripted movement etc.
var shouldSkipNextEvent: bool = false

## If [member shouldJoystickAimingSuppressMouse], then any movement of any gamepad joystick sets this flag if [member aimDirection] is not (0,0).
## This resolves conflicts between components such as [MouseRotationComponent] vs. [TurningControlComponent],
## allowing the player to aim a gun or move a cursor with the Right Joystick (for example) by temporarily ignoring mouse motion.
## Clicking any mouse button disables this flag.
var shouldSuppressMouseMotion: bool = false:
	set(newValue):
		if newValue != shouldSuppressMouseMotion:
			shouldSuppressMouseMotion = newValue
			didToggleMouseSuppression.emit(shouldSuppressMouseMotion)

#endregion


#region Derived State
var turnInputSign: int: ## +1 if turning clockwise (right), -1 if counter-clockwise (left)
	get: return int(signf(turnInput))

var thrustInputSign: int: ## +1 if thrusting forward (up), -1 if backwards (down) ## ALERT: This is unlike [member verticalInput] where "up" is NEGATIVE!
	get: return int(signf(thrustInput))
#endregion


#region Signals

## Emitted after an [InputEvent] has been fully processed and all state properties have been updated.
## NOTE: AFTER [signal didUpdateInputActionsList]
## TIP: Other components/scripts should check the DERIVED properties like [member horizontalInput] instead of directly processing an [InputEvent] on their own.
## ALERT: This signal is NOT emitted if directly modifying properties such as [member movementDirection]
signal didProcessInput(event: InputEvent)

## Emitted when an [InputEvent] includes one of the [member inputActionsToMonitor] and the list of [member inputActionsPressed] is updated.
## NOTE: BEFORE [signal didProcessInput]
## ALERT: This signal is NOT emitted if directly modifying properties such as [member movementDirection]
signal didUpdateInputActionsList(event: InputEvent)

## Emitted after [member movementDirection] is updated with a non-zero [param difference]
## ALERT: This signal may be emitted BEFORE other properties are updated, such as [member horizontalInput] or [member verticalInput] or [member aimDirection] etc.
signal didUpdateMovementDirection(movementDirection: Vector2, difference: Vector2)

## Emitted when [member horizontalInput] and [member lastNonzeroHorizontalInput] have an OPPOSITE SIGN (positive/negative), signifying a flip between right ↔ left.
## Any 0 input is ignored, i.e. when movement stops but the direction doesn't change.
## May be used for sprite flipping and other animations etc.
signal didChangeHorizontalDirection

## Emitted when [member verticalInput] and [member lastNonzeroVerticalInput] have an OPPOSITE SIGN (positive/negative), signifying a flip between up ↔ down.
## Any 0 input is ignored, i.e. when movement stops but the direction doesn't change.
## May be used for sprite flipping and other animations etc.
signal didChangeVerticalDirection

## Emitted after [member aimDirection] is updated with a non-zero [param difference]
## ALERT: This signal may be emitted BEFORE other properties are updated, such as [member turnInput] or [member thrustInput] etc.
signal didUpdateAimDirection(aimDirection: Vector2,	difference: Vector2)

## Emitted after [member turnInput] is updated with a non-zero [param difference]
## ALERT: This signal may be emitted BEFORE other properties are updated, such as [member movementDirection] or [member aimDirection] etc.
signal didUpdateTurnInput(turnInput: float, difference: float)

## ALERT: This signal may be emitted BEFORE other properties are updated, such as [member movementDirection] or [member aimDirection] etc.
signal didUpdateThrustInput(thrustInput: float, difference: float)

## Emitted after [method resyncAllInputs] which may occur after [method _ready] or unpause/re-enable etc.
## TIP: This signal helps dependent components sync with the input state of buttons etc. that were held BEFORE the first update.
signal didResyncAllInputs

## Emitted after [method clearAllInputs] which may occur after [method _ready] or pause/unpause/enable/disable etc.
signal didClearAllInputs

## Emitted when [member shouldSuppressMouseMotion] is changed.
## Components such as [MouseRotationComponent] & [TurningControlComponent] must monitor this signal,
## to allow the player to aim a gun or move a cursor with the Right Joystick (for example) by temporarily ignoring mouse motion.
signal didToggleMouseSuppression(shouldSuppressMouse: bool)

#endregion


#region Initialization

func onParented() -> void:
	# Connect to onEntityDidReady() so we can let other components sync with the initial input state, independent of node _ready() order.
	self.shouldNotifyOnEntityReady = true # CHECK: Should this be done earlier, in _init() or something?
	super.onParented()


func _ready() -> void:
	setAllProcesses() # Apply setters because Godot doesn't on _ready()

	# UNUSED: Let _notification() handle syncing after pause/unpause
	# Tools.connectSignal(SceneManager.willSetPause, self.onWillSetPause)
	# Tools.connectSignal(SceneManager.didSetPause,  self.onDidSetPause)


## Enables or disables the per-frame and event processing according to the various flags.
func setAllProcesses() -> void:
	self.set_process(debugMode)
	self.set_process_input(isEnabled and isPlayerControlled and not shouldProcessUnhandledInputOnly)
	self.set_process_unhandled_input(isEnabled and isPlayerControlled and shouldProcessUnhandledInputOnly)


func onEntityDidReady() -> void:
	# NOTE: `shouldNotifyOnEntityReady` is set in onParented()
	# Sync with input actions that were pressed/released BEFORE _ready() and let other components sync with the input state before the first update.
	resyncAllInputs()

#endregion


#region Input Events

## Affected by [member isEnabled], [member isPlayerControlled] and [member shouldProcessUnhandledInputOnly]
## May be skipped ONCE by [member shouldSkipNextEvent]
func _input(event: InputEvent) -> void:
	# Checked by property setters: if isEnabled and not shouldProcessUnhandledInputOnly:
	if event is InputEventMouseMotion: return
	if shouldSkipNextEvent:
		shouldSkipNextEvent = false
		return
	if debugMode: printDebug(str("_input(): ", event))
	handleEvent(event)


## Affected by [member isEnabled], [member isPlayerControlled] and [member shouldProcessUnhandledInputOnly]
## May be skipped ONCE by [member shouldSkipNextEvent]
func _unhandled_input(event: InputEvent) -> void:
	# Checked by property setters: if isEnabled and shouldProcessUnhandledInputOnly:
	if event is InputEventMouseMotion: return
	if shouldSkipNextEvent:
		shouldSkipNextEvent = false
		return
	if debugMode: printDebug(str("_unhandled_input(): ", event))
	handleEvent(event)


## Sets the various vectors and flags such as [member movementDirection] based on the received [InputEvent] and [Input] state.
## Affected by [member isEnabled] but NOT affected by [member isPlayerControlled], to allow control by AI/code.
## ALERT: NOT affected by [member shouldSkipNextEvent], to allow manual processing of synthetic [InputEvent]s etc.
## NOTE: For joystick input, events will be raised TWICE: once for each X and Y axis.
func handleEvent(event: InputEvent) -> void:
	# TODO: Get axes from the `event` to allow AI control via generateEvent() (maybe via InputEventJoypadMotion etc.?)

	if not isEnabled: return
	if debugMode: printDebug(str("handleEvent(): ", event))

	# If we were suppressing mouse movement to prioritize the secondary joystick
	# and the player clicked ANY mouse button, un-suppress the mouse.
	if  self.shouldSuppressMouseMotion and event is InputEventMouseButton and event.is_pressed():
		self.shouldSuppressMouseMotion = false

	# All other events should only be processed if they match a registered input action and are not "echoes"
	if not event.is_action_type() \
	or (self.shouldIgnoreEchoes and event.is_echo()):
		return

	var didHandleEvent: bool
	self.lastInputEvent = event # NOTE: Update this BEFORE modifying state proeprties, so signal handlers for `didUpdateMovementDirection` etc. may inspect the event being processed. # TBD: Should there be an `isProcessingEvent` to disambiguate from "stale" `lastInputEvent`s when properties are manually modified?
	if processMonitoredInputActions(event): didHandleEvent = true

	# NOTE: Do NOT check is_action_pressed() or is_action_released()
	# because even if 1 directional input is pressed/released, an entire axis must be updated from the state of 2 input actions.
	# Analog joystick fractional input strengths must also be accounted for.

	# NOTE: Use separate `if` groups, NOT `else` or `elif` because these multiple sets of axes may have the SAME input mappings!
	# For example, "moveLeft" and "turnLeft" may be bound to the same joystick.

	# Primary Movement
	if event.is_action(GlobalInput.Actions.moveLeft)	\
	or event.is_action(GlobalInput.Actions.moveRight)	\
	or event.is_action(GlobalInput.Actions.moveUp)		\
	or event.is_action(GlobalInput.Actions.moveDown):

		# NOTE: get_vector() is "normalized" for diagonals e.g. up+right = (0.707, -0.707), get_axis() is "raw" e.g. (1.0, -1.0)
		resyncMovementInput()
		didHandleEvent		= true

	# Aim/Look (Right Stick)
	if event.is_action(GlobalInput.Actions.aimLeft)		\
	or event.is_action(GlobalInput.Actions.aimRight)	\
	or event.is_action(GlobalInput.Actions.aimUp)		\
	or event.is_action(GlobalInput.Actions.aimDown):
		self.aimDirection	= Input.get_vector(GlobalInput.Actions.aimLeft,	GlobalInput.Actions.aimRight, GlobalInput.Actions.aimUp, GlobalInput.Actions.aimDown) * aimDirectionScale
		didHandleEvent		= true

	# Turn (Left Stick)
	if event.is_action(GlobalInput.Actions.turnLeft) \
	or event.is_action(GlobalInput.Actions.turnRight):
		self.turnInput		= Input.get_axis(GlobalInput.Actions.turnLeft,	GlobalInput.Actions.turnRight)
		didHandleEvent		= true

	# Thrust (Left Stick)
	if event.is_action(GlobalInput.Actions.moveForward) \
	or event.is_action(GlobalInput.Actions.moveBackward):
		self.thrustInput	= Input.get_axis(GlobalInput.Actions.moveBackward, GlobalInput.Actions.moveForward)
		didHandleEvent		= true

	# Let the Stick rule over Mice?
	if event is InputEventJoypadMotion \
	and ((shouldJoystickMovementSuppressMouse and not self.movementDirection.is_zero_approx())
		or (shouldJoystickAimingSuppressMouse and not self.aimDirection.is_zero_approx())):
			self.shouldSuppressMouseMotion = true

	# Prevent the event from bubbling up to other nodes/components?
	if shouldSetEventsAsHandled and didHandleEvent: self.get_viewport().set_input_as_handled()

	if debugMode: showDebugInfo()
	didProcessInput.emit(event)


## Updates [member inputActionsPressed]
## Affected by [member isEnabled] but NOT affected by [member isPlayerControlled], to allow control by AI/code.
## Returns `true` if [param event] contains one of the input actions included in [constant inputActionsToMonitor]
func processMonitoredInputActions(event: InputEvent = null) -> bool:
	if not isEnabled: return false

	# DESIGN: Do NOT just listen for `event.is_action_pressed()` etc., poll the state of ALL input actions,
	# to make sure that [inputActionsPressed] also includes input actions that were pressed BEFORE this component received its first event.

	# TBD: CHECK: PERFORMANCE: What's faster? Just create a new array each time or modify an existing one?
	var inputActionsPressedUpdate: PackedStringArray
	var isEventMonitored: bool # Does the received InputEvent include one of the input actions we monitor?

	for inputActionName: StringName in inputActionsToMonitor:
		# Check all input actions, not just the ones in the current event, in case any actions were pressed before this component was ready.
		# NOTE: Input.is_action_pressed() will not detect "fake" events from generateEvent()
		if (event and event.is_action_pressed(inputActionName)) \
		or Input.is_action_pressed(inputActionName):
			inputActionsPressedUpdate.append(inputActionName)

		if event and event.is_action(inputActionName): # Check event because it may be null when doing a manual update
			isEventMonitored = true

	# Did we consume an InputEvent for one of the input actions we monitor?
	if isEventMonitored:
		if debugMode: printDebug(str("processMonitoredInputActions() event: ", event, ", inputActionsPressed: ", inputActionsPressed, " → ", inputActionsPressedUpdate))
		self.inputActionsPressed = inputActionsPressedUpdate
		didUpdateInputActionsList.emit(event)
		if debugMode and GlobalSonic: GlobalSonic.beep(440, 0.1)

	# Update (or clear) even if there was no event, in case this function was called from _ready() to get the state before this component was ready.
	elif event == null:
		self.inputActionsPressed = inputActionsPressedUpdate

	return isEventMonitored


## Repolls the [Input] state and updates all vector & axis properties like [member movementDirection], [member turnInput] etc.
## NOTE: If not [member isEnabled], then only [member clearAllInputs] is called and the [Input] state is NOT polled.
func resyncAllInputs() -> void:
	if debugMode: printDebug(str("resyncAllInputs() isEnabled: ", isEnabled))
	if not isEnabled:
		clearAllInputs()
		return
	resyncMovementInput()
	self.aimDirection		= Input.get_vector(GlobalInput.Actions.aimLeft,	GlobalInput.Actions.aimRight,  GlobalInput.Actions.aimUp,  GlobalInput.Actions.aimDown)  * aimDirectionScale
	self.turnInput			= Input.get_axis(  GlobalInput.Actions.turnLeft,GlobalInput.Actions.turnRight)
	self.thrustInput		= Input.get_axis(  GlobalInput.Actions.moveBackward, GlobalInput.Actions.moveForward)
	# CHECK: TBD: "Replay" held inputs? e.g. a Fire button that was pressed throughout the pause and is still pressed after unpausing?
	# DESIGN: Maybe it is more intuitive if the player has to press Fire etc. again after unpausing; held buttons should be ignored.
	processMonitoredInputActions(null) # Sync Jump, Fire etc.
	didResyncAllInputs.emit()


## Updates [member movementDirection] & [member horizontalInput] & [member verticalInput] directly from the current [Input] state.
## Signals such as [signal didUpdateMovementDirection] are emitted in turn as each property is modified.
## NOTE: Does NOT check any [InputEvent]
func resyncMovementInput() -> void:
	# NOTE: get_vector() is "normalized" for diagonals e.g. up+right = (0.707, -0.707), get_axis() is "raw" e.g. (1.0, -1.0)
	# NOTE: Update `movementDirection` last so signal handlers for `didUpdateMovementDirection` can see the updated axes too
	self.horizontalInput	= Input.get_axis(GlobalInput.Actions.moveLeft,	 GlobalInput.Actions.moveRight) * movementDirectionScale.x
	self.verticalInput		= Input.get_axis(GlobalInput.Actions.moveUp,	 GlobalInput.Actions.moveDown)  * movementDirectionScale.y	
	self.movementDirection	= Input.get_vector(GlobalInput.Actions.moveLeft, GlobalInput.Actions.moveRight, GlobalInput.Actions.moveUp, GlobalInput.Actions.moveDown) * movementDirectionScale

#endregion


#region Pause/Unpause
# FIXES: Handle cases where pressing e.g. the Right Arrow Key, then pressing Pause BEFORE releasing Right, then releasing Right WHILE paused, and then unpausing, causes the character to keep moving right.

## Handle pause/unpause by other sources besides SceneManager
func _notification(what: int) -> void:
	match what:
		NOTIFICATION_PAUSED:	self.onDidSetPause(true)
		NOTIFICATION_UNPAUSED:	self.onDidSetPause(false)


@warning_ignore("unused_parameter")
func onWillSetPause(shouldPause: bool) -> void:
	pass # UNUSED: Update our state AFTER pause/unpause in onDidSetPause()


func onDidSetPause(isPaused: bool) -> void:
	if not isPlayerControlled: return # TBD: Should we do this even for AI-controlled entities?
	if debugMode: printDebug(str("onDidSetPause(): ", isPaused))

	if isPaused:
		self.clearAllInputs() # CHECK: TBD: Should we reset state here & emit signals?

	else: # Unpaused?
		if isEnabled: self.resyncAllInputs() # Calls processMonitoredInputActions() & emits `didResyncAllInputs`
		else: self.clearAllInputs()

#endregion


#region Modification

## Sets all properties to 0 & clears the [member inputActionsPressed] list.
## NOTE: Does NOT modify the "should" options: [shouldSkipNextEvent], [member shouldSuppressMouseMotion] etc.
func clearAllInputs() -> void:
	if debugMode: printDebug("clearAllInputs()")
	inputActionsPressed.clear()
	# TBD: Update order: Which signals to emit first?
	lastInputEvent				= null # NOTE: Clear this before modifying other properties, in case some setters access it.
	lastNonzeroHorizontalInput	= 0
	horizontalInput				= 0
	lastNonzeroVerticalInput	= 0
	verticalInput				= 0
	movementDirection			= Vector2.ZERO
	aimDirection				= Vector2.ZERO
	turnInput					= 0
	thrustInput					= 0
	didClearAllInputs.emit() # Let dependent components release "held" inputs like Jump/Fire etc.


## Zeroes [member horizontalInput] & [member verticalInput] & [member movementDirection] 
## If [param shouldClearLastNonzeroInput], also zeroes [member lastNonzeroHorizontalInput] & [member lastNonzeroVerticalInput] first.
## ALERT: Does NOT "re-normalize" diagonal inputs! i.e. clearing X from (0.707, 0.707) leaves (0, 0.707) NOT (0, 1)
func clearMovementInputs(shouldZeroX: bool = true, shouldZeroY: bool = true, shouldClearLastNonzeroInput: bool = false) -> void:
	if shouldClearLastNonzeroInput:
		if shouldZeroX: self.lastNonzeroHorizontalInput	= 0
		if shouldZeroY: self.lastNonzeroVerticalInput	= 0
	# TBD: Update order: Emit axes signals before `didUpdateMovementDirection`?
	if shouldZeroX and shouldZeroY:
		self.horizontalInput	 = 0
		self.verticalInput		 = 0
		self.movementDirection	 = Vector2.ZERO # Update once instead of emitting `didUpdateMovementDirection` 2 times
	elif shouldZeroX:
		self.horizontalInput	 = 0
		self.movementDirection.x = 0
	elif shouldZeroY:
		self.verticalInput		 = 0
		self.movementDirection.y = 0


## Directly modifies the [member movementDirection], applies scaling, and updates [member horizontalInput] & [member verticalInput] accordingly.
## NOTE: If [param shouldNormalize] is `true` (default), this method matches the behavior of actual input events,
## where [member movementDirection] is "normalized" for diagonals, polled via [method Input.get_vector] e.g. up+right = (0.707, -0.707),
## whereas [member horizontalInput] & [member verticalInput] are polled via [method Input.get_axis] e.g. up+right = (1.0, -1.0)
## WARNING: Do NOT pass pre-normalized values if [param shouldNormalize]
func setMovementInputs(newDirection: Vector2, scaleOverride: Vector2 = self.movementDirectionScale, shouldNormalize: bool = true) -> void:
	var scaledDirection: Vector2 = newDirection * scaleOverride
	# TBD: Update order: Emit axes signals before `didUpdateMovementDirection`?
	self.horizontalInput	= scaledDirection.x
	self.verticalInput		= scaledDirection.y
	self.movementDirection	= scaledDirection if not shouldNormalize else newDirection.limit_length(1.0) * scaleOverride


## Generates a "fake" [InputEventAction] with the specified input action name and calls [method handleEvent], for ONLY THIS component & its entity.
## If [param generateGlobalEvent], then a GLOBAL event is emitted, that may be processed by ALL components & scripts in their [method _input] handler.
## May be used by AI agents or "demo" scripts etc.
## NOTE: [member movementDirection] and other vectors are polled from the global [Input] state in [method handleEvent]
## ALERT: May NOT "fool" [method Input.is_action_just_pressed] or [method Input.get_axis] etc. unless [param generateGlobalEvent] is `true`.
func generateEvent(inputActionName: StringName, generateGlobalEvent: bool = false, pressed: bool = true, strength: float = 1 if pressed else 0, setAsHandled: bool = self.shouldSetEventsAsHandled) -> InputEvent:
	# TODO: Fix Input.is_action_just_pressed() etc.
	# TODO: CHECK: Synthesize analog axes events like InputEventJoypadMotion etc.
	if debugMode and isEnabled: printDebug(str("generateEvent(): ", inputActionName, ", generateGlobalEvent: ", generateGlobalEvent, ", pressed: ", pressed, ", strength: ",  strength))

	if not isEnabled or inputActionName.is_empty(): return null

	if shouldSkipNextEvent:
		shouldSkipNextEvent = false
		return null

	# Forge the event
	var event: InputEventAction = InputEventAction.new()
	event.action   = inputActionName
	event.pressed  = pressed
	event.strength = strength

	if debugMode: printDebug(str(event))

	# Fire it!
	if generateGlobalEvent: Input.parse_input_event(event) # TBD: Call GlobalInput.generateInputEvent() in case it does extra validation/processing etc.?

	# NOTE: If we're player-controlled, then handleEvent() will be called by the global event → _input() or _unhandled_input() anyway.
	# If not, we need to manually handle our own generated event.
	if not generateGlobalEvent or not self.isPlayerControlled: self.handleEvent(event)

	if setAsHandled: self.get_viewport().set_input_as_handled() # CHECK: Does this matter outside _input()/_unhandled_input()?

	return event

#endregion


#region Debugging

func _process(_delta: float) -> void:
	if debugMode: showDebugInfo()


func showDebugInfo() -> void:
	# if not debugMode: return # Checked by caller
	Debug.addComponentWatchList(self, {
		actionsPressed		= inputActionsPressed,
		movementDirection	= movementDirection,
		aimDirection		= aimDirection,
		horizontalInput		= horizontalInput,
		verticalInput		= verticalInput,
		turnInput			= turnInput,
		thrustInput			= thrustInput
		})

#endregion
