blank_issues_enabled: false

contact_links:
  - name: GòómDev Discord
    url: https://discord.gg/jZG3cBFt7u
    about: Ping @Syntaks.io on Discord for stuff about Comedot, or just chill with other devs while devving your goom.
